const output=document.querySelector('#results'),frame=document.querySelector('#preview');
const id='00000000-1111-4222-8333-000000000001';
const pause=()=>new Promise(resolve=>setTimeout(resolve,20));
const win=()=>frame.contentWindow, doc=()=>frame.contentDocument, el=s=>doc().querySelector(s);
function assert(value,message='Assertion failed'){if(!value)throw Error(message);}
async function until(fn){const start=Date.now();while(!fn()){if(Date.now()-start>6000)throw Error('Timed out waiting for UI');await pause();}}
async function load(path){frame.src='/__qa/'+path;await new Promise(resolve=>frame.onload=resolve);await until(()=>win().testState);}
function fill(selector,value){el(selector).value=value;el(selector).dispatchEvent(new (win().Event)('input',{bubbles:true}));}
function submit(selector){el(selector).requestSubmit();}
const includes=(selector,text)=>el(selector)?.textContent.includes(text);
document.querySelector('#run').onclick=async()=>{
 document.querySelector('#run').disabled=true;output.textContent='Running isolated browser checks…\n';let passed=0;const errors=[];
 const check=async(name,fn)=>{await fn();passed++;output.textContent+='PASS '+name+'\n';};
 frame.addEventListener('load',()=>win().addEventListener('error',event=>errors.push(event.message)));
 try{
 await check('Navigation, blank profile, and buy-only order form',async()=>{await load('index.html');el('a[href="#profile"]').click();await until(()=>doc().body.classList.contains('setup-mode'));assert(win().getComputedStyle(el('#order')).display==='none');assert(el('#name').value==='');});
 await check('One auth client, no nested auth session call',async()=>{await until(()=>win().testState.sessionCalls===1);assert(win().testState.clients===1);assert(errors.length===0);});
 await check('Email link request and resend cooldown',async()=>{fill('#signin-email','athlete@example.com');submit('#signin-form');await until(()=>includes('#auth-note','Check your inbox'));assert(el('#signin-form button').disabled);assert(win().testState.calls.filter(x=>x[0]==='email').length===1);});
 await check('Sign-in enables saving without hanging',async()=>{win().testSignIn();await until(()=>!el('#save-profile').disabled);assert(!el('#signout').hidden);});
 await check('Unsafe highlight URLs are rejected before saving',async()=>{fill('#name','QA Athlete');fill('#sport','Soccer');fill('#grad','2028');fill('#highlight','javascript:alert(1)');submit('#athlete-form');await until(()=>includes('#profile-status','valid http'));assert(!win().testState.calls.some(x=>x[0]==='save'));});
 let slug;
 await check('Publish/save shows profile link and saves extended fields',async()=>{fill('#highlight','hudl.com/example');fill('#stats','2026: 12 goals');el('#is-public').checked=true;submit('#athlete-form');await until(()=>includes('#profile-status','saved and published'));slug=win().testState.profile.slug;assert(win().testState.profile.details.stats==='2026: 12 goals');assert(el('#public-link').href.includes(slug));});
 await check('Name changes preserve profile link',async()=>{fill('#name','Renamed QA Athlete');submit('#athlete-form');await until(()=>includes('#profile-status','saved and published'));assert(win().testState.profile.slug===slug);});
 await check('Save failure displays error and button recovers',async()=>{win().testState.failSave=true;submit('#athlete-form');await until(()=>includes('#profile-status','Save rejected'));assert(!el('#save-profile').disabled);win().testState.failSave=false;submit('#athlete-form');await until(()=>includes('#profile-status','saved and published'));});
 await check('Coach inbox renders untrusted text safely',async()=>{win().testState.messages=[{coach_name:'<img src=x onerror=alert(1)>',coach_email:'coach@example.com',message:'Interested in speaking with you.',created_at:new Date().toISOString()}];el('#refresh-inbox').click();await until(()=>includes('#inbox','Interested'));assert(!el('#inbox img'));});
 await check('Mobile setup has no horizontal overflow',async()=>{assert(doc().documentElement.scrollWidth<=win().innerWidth,'Setup overflows phone');});
 await check('Sign-out clears private fields and inbox',async()=>{el('#signout').click();await until(()=>includes('#auth-note','signed out'));await until(()=>el('#save-profile').disabled);assert(el('#name').value==='');assert(el('#athlete-workspace').hidden);});
 await check('Activation requires profile and handles invalid code',async()=>{await load('activate.html');win().testSignIn();await until(()=>!el('#activate-form').hidden);fill('#activation-code','UNKNOWN-CODE');submit('#activate-form');await until(()=>includes('#note','Save your athlete profile'));win().testState.profile={id,slug:'qa-athlete',is_public:true};submit('#activate-form');await until(()=>includes('#note','not found'));assert(!el('#activate-form button').disabled);});
 await check('Activation and retry return public profile link',async()=>{for(let n=0;n<2;n++){fill('#activation-code','VALID-CODE-123456');submit('#activate-form');await until(()=>includes('#note','Your card is connected'));}assert(!el('#activation-links').hidden);});
 await check('Missing public profile never loads a sample athlete',async()=>{await load('profile.html');await until(()=>includes('#profile-page','Incomplete profile link'));assert(el('#share').hidden);await load('profile.html?athlete=missing-athlete');await until(()=>includes('#profile-page','Profile not available'));});
 await check('Malformed and unactivated card links have useful states',async()=>{await load('card.html?card=bad');await until(()=>includes('#card-status','incomplete'));await load('card.html?card=00000000-1111-4222-8333-000000000002');await until(()=>includes('#card-status','no public profile'));});
 await check('Failed checkout retries reuse order ID and do not show payment link',async()=>{await load('index.html#buy');win().testState.failOrder=true;fill('#order-email','qa@example.invalid');el('#order-form [name="terms_acknowledgment"]').checked=true;el('#order-form [name="adult_purchaser"]').checked=true;submit('#order-form');await until(()=>includes('#order-note','Order failed'));const first=win().testState.calls.find(x=>x[0]==='reserve_scoutcard_order_email_only')[1].request_id;assert(!el('#order-form button').disabled);assert(el('#checkout-resume').hidden);submit('#order-form');await until(()=>includes('#order-note','Order failed'));assert(win().testState.calls.filter(x=>x[0]==='reserve_scoutcard_order_email_only')[1][1].request_id===first);});
 await check('Successful checkout includes order reference and email',async()=>{win().testState.failOrder=false;win().__qaCheckout=url=>win().checkoutObserved=url;submit('#order-form');await until(()=>win().checkoutObserved);const url=new URL(win().checkoutObserved);assert(url.hostname==='buy.stripe.com');assert(url.searchParams.get('prefilled_email')==='qa@example.invalid');assert(url.searchParams.get('client_reference_id')===win().testState.calls.find(x=>x[0]==='reserve_scoutcard_order_email_only')[1].request_id);assert(!el('#checkout-resume').hidden);});
 await check('Public profile safely renders athlete data and useful sections',async()=>{await load('profile.html?athlete=public-athlete&qa-public=1');await until(()=>el('#message-form'));assert(!el('#name img'));assert(el('#name').textContent.includes('<img'));assert(el('#highlight').hidden);assert(includes('#stats','12 goals'));assert(includes('#events','Showcase'));assert(!el('#print-profile').hidden);assert(doc().documentElement.scrollWidth<=win().innerWidth);});
 await check('Coach message form delivers to inbox and clears after success',async()=>{fill('#coach-name','Coach Example');fill('#coach-email','coach@example.invalid');fill('#coach-message','Hello, I would like to learn about your upcoming season.');submit('#message-form');await until(()=>includes('#message-note','delivered'));assert(el('#coach-message').value==='');assert(!el('#message-form button').disabled);assert(win().testState.calls.some(x=>x[0]==='send_coach_message'));});
 await check('Recruiting resume opens browser print/save PDF',async()=>{win().print=()=>win().printed=true;el('#print-profile').click();assert(win().printed===true);});
 assert(errors.length===0,errors.join('\n'));output.textContent+='\n'+passed+' checks passed. No real emails, payments, profiles or cards created.';
 }catch(error){output.textContent+='\nFAIL '+error.stack;}finally{document.querySelector('#run').disabled=false;}
};
